In [1]:
import numpy as np
from numpy import linalg

# Задание 1
Создайте numpy array с элементами от числа N до 0 (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).

In [2]:
n = int(input())

matrix = np.arange(n, -1, -1)
print(type(matrix))
print(matrix)

3
<class 'numpy.ndarray'>
[3 2 1 0]


# Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали.

In [13]:
n = int(input())

matrix_1 = np.diag(np.flip(np.arange(0, n+1)), k = 0)
print(matrix_1)

10
[[10  0  0  0  0  0  0  0  0  0  0]
 [ 0  9  0  0  0  0  0  0  0  0  0]
 [ 0  0  8  0  0  0  0  0  0  0  0]
 [ 0  0  0  7  0  0  0  0  0  0  0]
 [ 0  0  0  0  6  0  0  0  0  0  0]
 [ 0  0  0  0  0  5  0  0  0  0  0]
 [ 0  0  0  0  0  0  4  0  0  0  0]
 [ 0  0  0  0  0  0  0  3  0  0  0]
 [ 0  0  0  0  0  0  0  0  2  0  0]
 [ 0  0  0  0  0  0  0  0  0  1  0]
 [ 0  0  0  0  0  0  0  0  0  0  0]]


In [15]:
m = np.arange(0, n+1)
m

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [16]:
np.flip(m)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [11]:
print(matrix_1.sum())
print(np.trace(matrix_1))

55
55


# Задание 3
Решите систему уравнений:  

4x + 2y + z = 4  

x + 3y = 12  

5y + 4z = -3  


In [35]:
a = np.array([[4, 2, 1], [1, 3, 0], [0, 5, 4]])
b = np.array([4, 12, -3])

In [37]:
# решение 1
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [39]:
np.dot(a, b)

array([37, 40, 48])

In [42]:
# решение 2
from scipy.linalg import solve

solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [43]:
print(np.allclose(np.dot(a, linalg.solve(a, b)), b))
print(np.allclose(np.dot(a, solve(a, b)), b))

True
True


# Задание 4

Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя.     
Остальные столбцы - количество покупок категорий товаров этим пользователем:  

Матрица в виде numpy array

In [2]:
users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)

На сайт заходит очередной посетитель, о покупках которого известно следующее:

In [3]:
next_user_stats = np.array([0, 1, 2, 0, 0, 0])

Найдите самого похожего пользователя.   
Т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива users_stats

# Решение через модуль Numpy

In [10]:
dists = []
lines = len(users_stats)
i = 0
for i in range(lines):
    """
    Подсчет косинуса угла между векторами a, b по их координатам
    """
    # длины векторов
    aLength = np.linalg.norm(users_stats[i])
    bLength = np.linalg.norm(next_user_stats)
    cosine = round(np.dot(users_stats[i], next_user_stats) / (aLength * bLength), 2)
    dists.append({"index_user": i, "distance": float(cosine), "vector": users_stats[i]}) 
    """
    создание результирующщего словаря из которого будет найдено max значение косинусного сходства между user'ами
    """
    i += 1

In [11]:
dists

[{'index_user': 0, 'distance': 0.2, 'vector': array([2, 1, 0, 0, 0, 0])},
 {'index_user': 1, 'distance': 0.85, 'vector': array([1, 1, 2, 1, 0, 0])},
 {'index_user': 2, 'distance': 0.4, 'vector': array([2, 0, 1, 0, 0, 0])},
 {'index_user': 3, 'distance': 0.79, 'vector': array([1, 1, 2, 1, 0, 1])},
 {'index_user': 4, 'distance': 0.4, 'vector': array([0, 0, 1, 2, 0, 0])},
 {'index_user': 5, 'distance': 0.0, 'vector': array([0, 0, 0, 0, 0, 5])},
 {'index_user': 6, 'distance': 0.0, 'vector': array([1, 0, 0, 0, 0, 0])},
 {'index_user': 7, 'distance': 0.95, 'vector': array([0, 1, 1, 0, 0, 0])},
 {'index_user': 8, 'distance': 0.0, 'vector': array([0, 0, 0, 1, 1, 3])},
 {'index_user': 9, 'distance': 0.0, 'vector': array([1, 0, 0, 2, 1, 4])}]

### Ответ: юзер с индесом 7, вектор [0, 1, 1, 0, 0, 0]

# Решение через модуль Scipy

In [16]:
from scipy.spatial.distance import cosine

In [122]:
dists = []
lines = len(users_stats)
i = 0
for i in range(lines):
    dists.append({"index_user": i, "distance": round(cosine(users_stats[i], next_user_stats), 2)})
    i += 1

In [123]:
dists

[{'index_user': 0, 'distance': 0.8},
 {'index_user': 1, 'distance': 0.15},
 {'index_user': 2, 'distance': 0.6},
 {'index_user': 3, 'distance': 0.21},
 {'index_user': 4, 'distance': 0.6},
 {'index_user': 5, 'distance': 1.0},
 {'index_user': 6, 'distance': 1.0},
 {'index_user': 7, 'distance': 0.05},
 {'index_user': 8, 'distance': 1.0},
 {'index_user': 9, 'distance': 1.0}]

### Ответ: юзер с индесом 7, вектор [0, 1, 1, 0, 0, 0]

In [21]:
def cosine(users_stats, next_user_stats):
    aLength = np.linalg.norm(users_stats, axis = 1)
    bLength = np.linalg.norm(next_user_stats)
    cosine = np.dot(users_stats, next_user_stats) / (aLength * bLength)
    return cosine

In [22]:
cosine(users_stats, next_user_stats)

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])

In [19]:
np.dot(users_stats, next_user_stats)

array([1, 5, 2, 5, 2, 0, 0, 3, 0, 0])

In [20]:
(aLength * bLength)

10.488088481701517