In [37]:
import numpy as np
from sympy import *

## Домашнее задание

● Создайте случайную матрицу А1 размерностью 5 на 5  
● Транспонируйте матрицу A1  
● Найдите обратную матрицу для А1  
● Создайте диагональную матрицу - поэлементно перемножив единичную  
матрицу I и случайную матрицу A2 размерности 4 на 4  
● Создайте нулевую матрицу размерности 3 на 3  
● Для всех полученных матриц найдите: определитель, ранг и собственные значения  
● Проанализируйте результаты  

### Создайте случайную матрицу А1 размерностью 5 на 5

In [49]:
A1 = np.random.random_integers(1, 20, size = (5, 5))
A1

<ipython-input-49-0ffb114db94f>:1: DeprecationWarning: This function is deprecated. Please call randint(1, 20 + 1) instead
  A1 = np.random.random_integers(1, 20, size = (5, 5))


array([[ 1, 12, 12,  9, 14],
       [17, 17,  8, 10, 16],
       [13, 13, 12,  3, 13],
       [19, 10,  6,  5,  3],
       [20, 15, 20, 13, 10]])

### Транспонируйте матрицу A1

In [50]:
A1 = A1.transpose()
A1

array([[ 1, 17, 13, 19, 20],
       [12, 17, 13, 10, 15],
       [12,  8, 12,  6, 20],
       [ 9, 10,  3,  5, 13],
       [14, 16, 13,  3, 10]])

### Найдите обратную матрицу для А1

In [51]:
A_inv = np.linalg.inv(A1)
A_inv

array([[-0.14305293,  0.34400317,  0.00229945, -0.02939027, -0.19629043],
       [ 0.08207955, -0.21377231, -0.07508985,  0.09883048,  0.17819943],
       [ 0.02278126, -0.02667966,  0.05466894, -0.13583481,  0.06170433],
       [-0.10269842,  0.4411281 , -0.02719742, -0.08284096, -0.29420722],
       [ 0.07014071, -0.23722361,  0.05401413,  0.08445514,  0.09773406]])

### Создайте диагональную матрицу - поэлементно перемножив единичную матрицу I и случайную матрицу A2 размерности 4 на 4

In [56]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [57]:
A2 = np.random.random((4, 4))
A2

array([[0.67895873, 0.01165327, 0.40013449, 0.69217584],
       [0.14520786, 0.01379263, 0.04090718, 0.30451367],
       [0.04500292, 0.52925396, 0.01123009, 0.82236048],
       [0.8600829 , 0.34521738, 0.4172863 , 0.66572719]])

In [59]:
Diag_matrix = I * A2
Diag_matrix

array([[0.67895873, 0.        , 0.        , 0.        ],
       [0.        , 0.01379263, 0.        , 0.        ],
       [0.        , 0.        , 0.01123009, 0.        ],
       [0.        , 0.        , 0.        , 0.66572719]])

### Создайте нулевую матрицу размерности 3 на 3

In [55]:
Zeros_matrix = np.zeros((3, 3))
Zeros_matrix

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Для всех полученных матриц найдите: определитель, ранг и собственные значения

In [71]:
dict_matrix = {'A1': A1, 
               'A_inv': A_inv,
               'I': I,
               'A2': A2,
               'Diag_matrix': Diag_matrix,
               'Zeros_matrix': Zeros_matrix}

In [72]:
for key, value in dict_matrix.items():
    print(f'Определитель матрицы {key}: {round(np.linalg.det(value), 2)}')
    print('=================================================================')

Определитель матрицы A1: -65668.0
Определитель матрицы A_inv: -0.0
Определитель матрицы I: 1.0
Определитель матрицы A2: -0.02
Определитель матрицы Diag_matrix: 0.0
Определитель матрицы Zeros_matrix: 0.0


In [73]:
for key, value in dict_matrix.items():
    print(f'Ранг матрицы {key}: {round(np.linalg.matrix_rank(value), 2)}')
    print('=================================================================')

Ранг матрицы A1: 5
Ранг матрицы A_inv: 5
Ранг матрицы I: 4
Ранг матрицы A2: 4
Ранг матрицы Diag_matrix: 4
Ранг матрицы Zeros_matrix: 0


In [74]:
for key, value in dict_matrix.items():
    w, v = np.linalg.eig(value)
    print(f'Собственное значение матрицы {key}: {np.array(w, dtype=float)}')
    print('=================================================================')

Собственное значение матрицы A1: [ 59.16899225 -12.6598912   -3.41086887  -3.41086887   5.31263668]
Собственное значение матрицы A_inv: [-0.20670239 -0.20670239  0.18823045 -0.07898962  0.01690074]
Собственное значение матрицы I: [1. 1. 1. 1.]
Собственное значение матрицы A2: [ 1.74464355 -0.28839339 -0.04327076 -0.04327076]
Собственное значение матрицы Diag_matrix: [0.67895873 0.01379263 0.01123009 0.66572719]
Собственное значение матрицы Zeros_matrix: [0. 0. 0.]


<ipython-input-74-6693f7c3c57b>:3: ComplexWarning: Casting complex values to real discards the imaginary part
  print(f'Собственное значение матрицы {key}: {np.array(w, dtype=float)}')
